verbingone = input("Enter a verb ending in ing:")
pluralnounone = input("Choose a pluarl noun:")
nounone = input("Now choose a regular noun:")
pluralnountwo = input("Now a second plural noun:")
verbingtwo = input("And a second verb ending in ing?")
adjone = input("What about an adjective?")
verbone = input("And a regular verb?")
nountwo = input("Now choose your second noun:")
nounthree = input("Type in a third noun:")
pluralnounthree = input("And a third plural noun, please:")
adjtwo = input("We're gonna need another adjective:")
adjthree = input("And another adjective:")
print("I swear we're almost done")
bodyone = input("Give me a part of the body in its plural form:")
pluralnounfour = input("How does another plural noun sound?")
numberone = input("And lastly, I'm gonna need a number:")
input("Alright, ready?")
print("Presenting: Watto's Junk Shop")
print("If you're " + verbingone + " in the Outer Rim Territories and you need spare " + pluralnounone + " for your space-" + nounone + " or " + pluralnountwo + ", the place to go is Watto's Junk Shop.")
print("Here you can find everything from robots that talk like " + verbingtwo + " professionals to replacement wires for your " + adjone + " droid so that it can " + verbone + " until it runs out of " + nountwo + "." )
print("Be careful where you keep your " + nounthree + " because Watto doesn't take Republic credits, but he will take " + pluralnounthree + ".")
print("You may have to barter with something " + adjtwo + " that you own.")
print("The greedy and " + adjthree + " Watto would love to get his grimy " + bodyone + " on anything that's precious to you.")
print("And don't even think about using a Jedi Mind trick on Watto - when he says something costs ten " + pluralnounfour + ", you'd better pay up or he'll raise the price to " + numberone + " " + pluralnounfour + "!")
print("The end")
